# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.auto", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1243108090);
user_pref("app.update.lastUpdateTime.background-update-timer", 1243108090);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1243108090);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1242676783);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1243156646);
user_pref("browser.download.dir", "/home/rossi/Downloads");
user_pref("browser.download.folderList", 2);
user_pref("browser.download.lastDir", "/home/rossi/Dokumente");
user_pref("browser.download.save_converter_index", 0);
user_pref("browser.feeds.showFirstRunUI", false);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.history_expire_days_min", 3);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.preferences.advanced.selectedTabIndex", 1);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.0.10");
user_pref("browser.startup.page", 0);
user_pref("capability.policy.maonoscript.javascript.enabled", "allAccess");
user_pref("capability.policy.maonoscript.sites", "addons.mozilla.org cineplex.de flashgot.net google.com googlesyndication.com hotmail.com informaction.com live.com maone.net msn.com noscript.net passport.com passport.net passportimages.com yahoo.com yimg.com about: about:blank about:certerror about:config about:credits about:neterror about:plugins about:privatebrowsing about:sessionrestore chrome: file://cineplex.de file://flashgot.net file://google.com file://googlesyndication.com file://hotmail.com file://informaction.com file://live.com file://maone.net file://msn.com file://noscript.net file://passport.com file://passport.net file://passportimages.com file://yahoo.com file://yimg.com http://cineplex.de http://flashgot.net http://google.com http://googlesyndication.com http://hotmail.com http://informaction.com http://live.com http://maone.net http://msn.com http://noscript.net http://passport.com http://passport.net http://passportimages.com http://yahoo.com http://yimg.com https://cineplex.de https://flashgot.net https://google.com https://googlesyndication.com https://hotmail.com https://informaction.com https://live.com https://maone.net https://msn.com https://noscript.net https://passport.com https://passport.net https://passportimages.com https://yahoo.com https://yimg.com resource:");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.disable_window_move_resize", true);
user_pref("dom.event.contextmenu.enabled", false);
user_pref("extensions.adblockplus.currentVersion", "1.0.2");
user_pref("extensions.enabledItems", "{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}:1.0.2,langpack-de@firefox-3.0.ubuntu.com:3.0.7,langpack-en-GB@firefox-3.0.ubuntu.com:3.0.7,{73a6fe31-595d-460b-a920-fcc0f8843232}:1.9.2.8,langpack-de@xulrunner-1.9.ubuntu.com:1.9.0.8,langpack-en-GB@xulrunner-1.9.ubuntu.com:1.9.0.8,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.0.10");
user_pref("extensions.lastAppVersion", "3.0.10");
user_pref("extensions.update.notifyUser", false);
user_pref("intl.charsetmenu.browser.cache", "us-ascii, ISO-8859-15, ISO-8859-1, UTF-8, windows-1252");
user_pref("javascript.enabled", true);
user_pref("network.cookie.lifetimePolicy", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.autoconfig_url", "src/test/resources/pac/test1.pac");
user_pref("network.proxy.ftp", "ftp_proxy.unit-test.invalid");
user_pref("network.proxy.ftp_port", 8092);
user_pref("network.proxy.gopher", "gopher_proxy.unit-test.invalid");
user_pref("network.proxy.gopher_port", 8093);
user_pref("network.proxy.http", "http_proxy.unit-test.invalid");
user_pref("network.proxy.http_port", 8090);
user_pref("network.proxy.socks", "socks_proxy.unit-test.invalid");
user_pref("network.proxy.socks_port", 8095);
user_pref("network.proxy.socks_version", 4);
user_pref("network.proxy.ssl", "https_proxy.unit-test.invalid");
user_pref("network.proxy.ssl_port", 8091);
user_pref("network.proxy.type", 2);
user_pref("noscript.badInstall", false);
user_pref("noscript.global", true);
user_pref("noscript.gtemp", "");
user_pref("noscript.notify", false);
user_pref("noscript.options.tabSelectedIndexes", "5,4,1");
user_pref("noscript.policynames", "");
user_pref("noscript.temp", "");
user_pref("noscript.version", "1.9.2.8");
user_pref("pref.advanced.javascript.disable_button.advanced", false);
user_pref("pref.downloads.disable_button.edit_actions", false);
user_pref("privacy.item.offlineApps", true);
user_pref("signon.rememberSignons", false);
user_pref("spellchecker.dictionary", "de_AT");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1243725238);
